### ISSUE TITLE
I can't build this repository

### ISSUE THREAD

**Issue by gfx** [touchlab/android-orm-benchmark-updated#1]
First of all, you have to add `gradle/wrapper/gradle-wrapper.jar` to fix the gradle version, or use `./gradlew`.

And after I have added gradle-wrapper.jar, I got the following error on `./gradlew tasks`:

```
A problem occurred configuring project ':ORM-Benchmark'.
> Could not resolve all dependencies for configuration ':ORM-Benchmark:_debugCompile'.
   > Could not resolve co.touchlab.squeaky:squeaky-query:0.4.0.0.
     Required by:
         android-orm-benchmark-updated:ORM-Benchmark:unspecified
      > Could not resolve co.touchlab.squeaky:squeaky-query:0.4.0.0.
         > Could not get resource 'http://oss.jfrog.org/artifactory/oss-snapshot-local/co/touchlab/squeaky/squeaky-query/0.4.0.0/squeaky-query-0.4.0.0.pom'.
            > Could not GET 'http://oss.jfrog.org/artifactory/oss-snapshot-local/co/touchlab/squeaky/squeaky-query/0.4.0.0/squeaky-query-0.4.0.0.pom'. Received status code 409 from server: Conflict
```

Please setup a CI (Circle CI or anything), which helps you to make a repository portable.

**Comment by kpgalligan** [comment]
Squeaky version hasn't been pushed.  Uses mavenlocal.  Can build and use that for today from here: https://github.com/touchlab/Squeaky

**Comment by gfx** [comment]
That's too bad. Please setup CI to make a repo portable.

**Comment by AlexTrotsenko** [comment]
Just to keep it posted: I was able to build this repo now.
